global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'poznandevops@gmail.com'
  smtp_auth_username: 'poznandevops@gmail.com'
  smtp_auth_password: '{{ smtp_password }}'
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'andrzej.pusty@gmail.com'
        send_resolved: true
